language: node_js
node_js: 9
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker;' -U postgres
- psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
notifications: email: false
deploy:
  provider: heroku
  api_key:
    secure: KOlPk1wo+inImXY7Qb90pHv/M5/5Uod8BslY1fcZQE2FMVlET8Yp0D4UGUZc6x5wdtdLq8Rcy0hCtT+/yiEtGLmtuTH9OfwEarX81po9oa6eews5wN7pl9a8LzfyPlOSLxVFh4ieYjfcmTpDT9hCb9MpEGeghqNefFVOhiQsWNDcq/R4dViI/pKq55qhKddOYerLn5pprGX0V47peXWbOZ9W3H6XipBsQvb7+8IdXCQ3ObbveMcNV63sxYW3mIANKQ/NlfYQxCsBvfv16OaMKQr4Ho84lA7R/cYG7qqwVDE51maoNnNuT3axxjnvrhfKVZIt2Iz0kVPvHTKlIsTPYWbO4oJTp2rE0vqz2oRMJcs+KiO74sGrDqCZJ4VHgwC8EDgWYOtvOYR8cFEBDOPoTwYUdhmdg7IWDnNQFfjsatKPH/IyFeK4ZXmCKi9Z6EHPfaoU/aUFWmRiKezWhjgwT9B4ZfpUzXRoLt1zFifDMy3cyefh4JLk+zJFIOkYpgUUJmPq0yArR1zfnzq1zQiEIAT1221mfAzXXNy/LTNy13mi+7h/D5q2jmapXIE5silGgukdqboDoylqLY0LgeXB0K6mJC98X+dtCQ8xKlPmVMrNUTtTBhdqEk9yz/IJD1/DwN88j9MfUDkpnf8c1ExaI8Bc5JEL8f+ZRBK2+e2pA+4=
  app: pal-pick
  skip_cleanup: true